FROM golang:1.25-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o seeder cmd/seeder/main.go

FROM alpine:3.18 AS runtime
WORKDIR /app
COPY --from=build /app/seeder .
ENTRYPOINT ["./seeder"]