// Code generated by MockGen. DO NOT EDIT.
// Source: product.go
//
// Generated by this command:
//
//	mockgen -source=product.go -destination=./mocks/product_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/valeragav/avito-pvz-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockproductRepo is a mock of productRepo interface.
type MockproductRepo struct {
	ctrl     *gomock.Controller
	recorder *MockproductRepoMockRecorder
	isgomock struct{}
}

// MockproductRepoMockRecorder is the mock recorder for MockproductRepo.
type MockproductRepoMockRecorder struct {
	mock *MockproductRepo
}

// NewMockproductRepo creates a new mock instance.
func NewMockproductRepo(ctrl *gomock.Controller) *MockproductRepo {
	mock := &MockproductRepo{ctrl: ctrl}
	mock.recorder = &MockproductRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductRepo) EXPECT() *MockproductRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockproductRepo) Create(ctx context.Context, product domain.Product) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, product)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockproductRepoMockRecorder) Create(ctx, product any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockproductRepo)(nil).Create), ctx, product)
}

// DeleteProduct mocks base method.
func (m *MockproductRepo) DeleteProduct(ctx context.Context, productID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", ctx, productID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockproductRepoMockRecorder) DeleteProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockproductRepo)(nil).DeleteProduct), ctx, productID)
}

// GetLastProductInReception mocks base method.
func (m *MockproductRepo) GetLastProductInReception(ctx context.Context, receptionID uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastProductInReception", ctx, receptionID)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastProductInReception indicates an expected call of GetLastProductInReception.
func (mr *MockproductRepoMockRecorder) GetLastProductInReception(ctx, receptionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastProductInReception", reflect.TypeOf((*MockproductRepo)(nil).GetLastProductInReception), ctx, receptionID)
}

// MockreceptionRepo is a mock of receptionRepo interface.
type MockreceptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionRepoMockRecorder
	isgomock struct{}
}

// MockreceptionRepoMockRecorder is the mock recorder for MockreceptionRepo.
type MockreceptionRepoMockRecorder struct {
	mock *MockreceptionRepo
}

// NewMockreceptionRepo creates a new mock instance.
func NewMockreceptionRepo(ctrl *gomock.Controller) *MockreceptionRepo {
	mock := &MockreceptionRepo{ctrl: ctrl}
	mock.recorder = &MockreceptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionRepo) EXPECT() *MockreceptionRepoMockRecorder {
	return m.recorder
}

// FindByStatus mocks base method.
func (m *MockreceptionRepo) FindByStatus(ctx context.Context, statusName domain.ReceptionStatusCode, filter domain.Reception) (*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, statusName, filter)
	ret0, _ := ret[0].(*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockreceptionRepoMockRecorder) FindByStatus(ctx, statusName, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockreceptionRepo)(nil).FindByStatus), ctx, statusName, filter)
}

// MockproductTypeRepo is a mock of productTypeRepo interface.
type MockproductTypeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockproductTypeRepoMockRecorder
	isgomock struct{}
}

// MockproductTypeRepoMockRecorder is the mock recorder for MockproductTypeRepo.
type MockproductTypeRepoMockRecorder struct {
	mock *MockproductTypeRepo
}

// NewMockproductTypeRepo creates a new mock instance.
func NewMockproductTypeRepo(ctrl *gomock.Controller) *MockproductTypeRepo {
	mock := &MockproductTypeRepo{ctrl: ctrl}
	mock.recorder = &MockproductTypeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductTypeRepo) EXPECT() *MockproductTypeRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockproductTypeRepo) Get(ctx context.Context, filter domain.ProductType) (*domain.ProductType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*domain.ProductType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockproductTypeRepoMockRecorder) Get(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockproductTypeRepo)(nil).Get), ctx, filter)
}

// MockpvzRepo is a mock of pvzRepo interface.
type MockpvzRepo struct {
	ctrl     *gomock.Controller
	recorder *MockpvzRepoMockRecorder
	isgomock struct{}
}

// MockpvzRepoMockRecorder is the mock recorder for MockpvzRepo.
type MockpvzRepoMockRecorder struct {
	mock *MockpvzRepo
}

// NewMockpvzRepo creates a new mock instance.
func NewMockpvzRepo(ctrl *gomock.Controller) *MockpvzRepo {
	mock := &MockpvzRepo{ctrl: ctrl}
	mock.recorder = &MockpvzRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpvzRepo) EXPECT() *MockpvzRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockpvzRepo) Get(ctx context.Context, filter domain.PVZ) (*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockpvzRepoMockRecorder) Get(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockpvzRepo)(nil).Get), ctx, filter)
}
