// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/valeragav/avito-pvz-service/internal/domain"
	dto "github.com/valeragav/avito-pvz-service/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockproductService is a mock of productService interface.
type MockproductService struct {
	ctrl     *gomock.Controller
	recorder *MockproductServiceMockRecorder
	isgomock struct{}
}

// MockproductServiceMockRecorder is the mock recorder for MockproductService.
type MockproductServiceMockRecorder struct {
	mock *MockproductService
}

// NewMockproductService creates a new mock instance.
func NewMockproductService(ctrl *gomock.Controller) *MockproductService {
	mock := &MockproductService{ctrl: ctrl}
	mock.recorder = &MockproductServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductService) EXPECT() *MockproductServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockproductService) Create(ctx context.Context, createIn dto.ProductCreate) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createIn)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockproductServiceMockRecorder) Create(ctx, createIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockproductService)(nil).Create), ctx, createIn)
}

// DeleteLastProduct mocks base method.
func (m *MockproductService) DeleteLastProduct(ctx context.Context, pvzID uuid.UUID) (*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastProduct", ctx, pvzID)
	ret0, _ := ret[0].(*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteLastProduct indicates an expected call of DeleteLastProduct.
func (mr *MockproductServiceMockRecorder) DeleteLastProduct(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastProduct", reflect.TypeOf((*MockproductService)(nil).DeleteLastProduct), ctx, pvzID)
}
