// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	pvz "github.com/VaLeraGav/avito-pvz-service/internal/service/pvz"
	gomock "go.uber.org/mock/gomock"
)

// MockproductsService is a mock of productsService interface.
type MockproductsService struct {
	ctrl     *gomock.Controller
	recorder *MockproductsServiceMockRecorder
	isgomock struct{}
}

// MockproductsServiceMockRecorder is the mock recorder for MockproductsService.
type MockproductsServiceMockRecorder struct {
	mock *MockproductsService
}

// NewMockproductsService creates a new mock instance.
func NewMockproductsService(ctrl *gomock.Controller) *MockproductsService {
	mock := &MockproductsService{ctrl: ctrl}
	mock.recorder = &MockproductsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductsService) EXPECT() *MockproductsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockproductsService) Create(ctx context.Context, createIn pvz.CreateIn) (*pvz.CreateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createIn)
	ret0, _ := ret[0].(*pvz.CreateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockproductsServiceMockRecorder) Create(ctx, createIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockproductsService)(nil).Create), ctx, createIn)
}

// List mocks base method.
func (m *MockproductsService) List(ctx context.Context, pvzListParams *pvz.PvzListParams) (*pvz.PvzListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pvzListParams)
	ret0, _ := ret[0].(*pvz.PvzListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockproductsServiceMockRecorder) List(ctx, pvzListParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockproductsService)(nil).List), ctx, pvzListParams)
}
