// Code generated by MockGen. DO NOT EDIT.
// Source: pvz.go
//
// Generated by this command:
//
//	mockgen -source=pvz.go -destination=./mocks/pvz_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	domain "github.com/valeragav/avito-pvz-service/internal/domain"
	listparams "github.com/valeragav/avito-pvz-service/pkg/listparams"
	gomock "go.uber.org/mock/gomock"
)

// MockpvzRepo is a mock of pvzRepo interface.
type MockpvzRepo struct {
	ctrl     *gomock.Controller
	recorder *MockpvzRepoMockRecorder
	isgomock struct{}
}

// MockpvzRepoMockRecorder is the mock recorder for MockpvzRepo.
type MockpvzRepoMockRecorder struct {
	mock *MockpvzRepo
}

// NewMockpvzRepo creates a new mock instance.
func NewMockpvzRepo(ctrl *gomock.Controller) *MockpvzRepo {
	mock := &MockpvzRepo{ctrl: ctrl}
	mock.recorder = &MockpvzRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpvzRepo) EXPECT() *MockpvzRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockpvzRepo) Create(ctx context.Context, pvz domain.PVZ) (*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pvz)
	ret0, _ := ret[0].(*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockpvzRepoMockRecorder) Create(ctx, pvz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockpvzRepo)(nil).Create), ctx, pvz)
}

// GetList mocks base method.
func (m *MockpvzRepo) GetList(ctx context.Context, pagination *listparams.Pagination) ([]*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, pagination)
	ret0, _ := ret[0].([]*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockpvzRepoMockRecorder) GetList(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockpvzRepo)(nil).GetList), ctx, pagination)
}

// ListPvzByAcceptanceDateAndCity mocks base method.
func (m *MockpvzRepo) ListPvzByAcceptanceDateAndCity(ctx context.Context, pagination *listparams.Pagination, startDate, endDate *time.Time) ([]*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPvzByAcceptanceDateAndCity", ctx, pagination, startDate, endDate)
	ret0, _ := ret[0].([]*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPvzByAcceptanceDateAndCity indicates an expected call of ListPvzByAcceptanceDateAndCity.
func (mr *MockpvzRepoMockRecorder) ListPvzByAcceptanceDateAndCity(ctx, pagination, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPvzByAcceptanceDateAndCity", reflect.TypeOf((*MockpvzRepo)(nil).ListPvzByAcceptanceDateAndCity), ctx, pagination, startDate, endDate)
}

// MockcityRepo is a mock of cityRepo interface.
type MockcityRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcityRepoMockRecorder
	isgomock struct{}
}

// MockcityRepoMockRecorder is the mock recorder for MockcityRepo.
type MockcityRepoMockRecorder struct {
	mock *MockcityRepo
}

// NewMockcityRepo creates a new mock instance.
func NewMockcityRepo(ctrl *gomock.Controller) *MockcityRepo {
	mock := &MockcityRepo{ctrl: ctrl}
	mock.recorder = &MockcityRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcityRepo) EXPECT() *MockcityRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockcityRepo) Get(ctx context.Context, filter domain.City) (*domain.City, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*domain.City)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockcityRepoMockRecorder) Get(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockcityRepo)(nil).Get), ctx, filter)
}

// MockreceptionRepo is a mock of receptionRepo interface.
type MockreceptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionRepoMockRecorder
	isgomock struct{}
}

// MockreceptionRepoMockRecorder is the mock recorder for MockreceptionRepo.
type MockreceptionRepoMockRecorder struct {
	mock *MockreceptionRepo
}

// NewMockreceptionRepo creates a new mock instance.
func NewMockreceptionRepo(ctrl *gomock.Controller) *MockreceptionRepo {
	mock := &MockreceptionRepo{ctrl: ctrl}
	mock.recorder = &MockreceptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionRepo) EXPECT() *MockreceptionRepoMockRecorder {
	return m.recorder
}

// ListByIDsWithStatus mocks base method.
func (m *MockreceptionRepo) ListByIDsWithStatus(ctx context.Context, receptionIDs []uuid.UUID) ([]*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByIDsWithStatus", ctx, receptionIDs)
	ret0, _ := ret[0].([]*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByIDsWithStatus indicates an expected call of ListByIDsWithStatus.
func (mr *MockreceptionRepoMockRecorder) ListByIDsWithStatus(ctx, receptionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByIDsWithStatus", reflect.TypeOf((*MockreceptionRepo)(nil).ListByIDsWithStatus), ctx, receptionIDs)
}

// MockproductRepo is a mock of productRepo interface.
type MockproductRepo struct {
	ctrl     *gomock.Controller
	recorder *MockproductRepoMockRecorder
	isgomock struct{}
}

// MockproductRepoMockRecorder is the mock recorder for MockproductRepo.
type MockproductRepoMockRecorder struct {
	mock *MockproductRepo
}

// NewMockproductRepo creates a new mock instance.
func NewMockproductRepo(ctrl *gomock.Controller) *MockproductRepo {
	mock := &MockproductRepo{ctrl: ctrl}
	mock.recorder = &MockproductRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductRepo) EXPECT() *MockproductRepoMockRecorder {
	return m.recorder
}

// ListByReceptionIDsWithTypeName mocks base method.
func (m *MockproductRepo) ListByReceptionIDsWithTypeName(ctx context.Context, receptionIDs []uuid.UUID) ([]*domain.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReceptionIDsWithTypeName", ctx, receptionIDs)
	ret0, _ := ret[0].([]*domain.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReceptionIDsWithTypeName indicates an expected call of ListByReceptionIDsWithTypeName.
func (mr *MockproductRepoMockRecorder) ListByReceptionIDsWithTypeName(ctx, receptionIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReceptionIDsWithTypeName", reflect.TypeOf((*MockproductRepo)(nil).ListByReceptionIDsWithTypeName), ctx, receptionIDs)
}
