// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/valeragav/avito-pvz-service/internal/domain"
	dto "github.com/valeragav/avito-pvz-service/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockreceptionService is a mock of receptionService interface.
type MockreceptionService struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionServiceMockRecorder
	isgomock struct{}
}

// MockreceptionServiceMockRecorder is the mock recorder for MockreceptionService.
type MockreceptionServiceMockRecorder struct {
	mock *MockreceptionService
}

// NewMockreceptionService creates a new mock instance.
func NewMockreceptionService(ctrl *gomock.Controller) *MockreceptionService {
	mock := &MockreceptionService{ctrl: ctrl}
	mock.recorder = &MockreceptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionService) EXPECT() *MockreceptionServiceMockRecorder {
	return m.recorder
}

// CloseLastReception mocks base method.
func (m *MockreceptionService) CloseLastReception(ctx context.Context, pvzID uuid.UUID) (*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseLastReception", ctx, pvzID)
	ret0, _ := ret[0].(*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseLastReception indicates an expected call of CloseLastReception.
func (mr *MockreceptionServiceMockRecorder) CloseLastReception(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseLastReception", reflect.TypeOf((*MockreceptionService)(nil).CloseLastReception), ctx, pvzID)
}

// Create mocks base method.
func (m *MockreceptionService) Create(ctx context.Context, createIn dto.ReceptionCreate) (*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createIn)
	ret0, _ := ret[0].(*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockreceptionServiceMockRecorder) Create(ctx, createIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockreceptionService)(nil).Create), ctx, createIn)
}
