// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	products "github.com/VaLeraGav/avito-pvz-service/internal/service/products"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockproductsService is a mock of productsService interface.
type MockproductsService struct {
	ctrl     *gomock.Controller
	recorder *MockproductsServiceMockRecorder
	isgomock struct{}
}

// MockproductsServiceMockRecorder is the mock recorder for MockproductsService.
type MockproductsServiceMockRecorder struct {
	mock *MockproductsService
}

// NewMockproductsService creates a new mock instance.
func NewMockproductsService(ctrl *gomock.Controller) *MockproductsService {
	mock := &MockproductsService{ctrl: ctrl}
	mock.recorder = &MockproductsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproductsService) EXPECT() *MockproductsServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockproductsService) Create(ctx context.Context, createIn products.CreateIn) (*products.CreateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createIn)
	ret0, _ := ret[0].(*products.CreateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockproductsServiceMockRecorder) Create(ctx, createIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockproductsService)(nil).Create), ctx, createIn)
}

// DeleteLastProduct mocks base method.
func (m *MockproductsService) DeleteLastProduct(ctx context.Context, pvzID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLastProduct", ctx, pvzID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLastProduct indicates an expected call of DeleteLastProduct.
func (mr *MockproductsServiceMockRecorder) DeleteLastProduct(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLastProduct", reflect.TypeOf((*MockproductsService)(nil).DeleteLastProduct), ctx, pvzID)
}
