// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	receptions "github.com/valeragav/avito-pvz-service/internal/service/receptions"
	gomock "go.uber.org/mock/gomock"
)

// MockreceptionsService is a mock of receptionsService interface.
type MockreceptionsService struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionsServiceMockRecorder
	isgomock struct{}
}

// MockreceptionsServiceMockRecorder is the mock recorder for MockreceptionsService.
type MockreceptionsServiceMockRecorder struct {
	mock *MockreceptionsService
}

// NewMockreceptionsService creates a new mock instance.
func NewMockreceptionsService(ctrl *gomock.Controller) *MockreceptionsService {
	mock := &MockreceptionsService{ctrl: ctrl}
	mock.recorder = &MockreceptionsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionsService) EXPECT() *MockreceptionsServiceMockRecorder {
	return m.recorder
}

// CloseLastReception mocks base method.
func (m *MockreceptionsService) CloseLastReception(ctx context.Context, pvzID uuid.UUID) (*receptions.CloseLastReceptionOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseLastReception", ctx, pvzID)
	ret0, _ := ret[0].(*receptions.CloseLastReceptionOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseLastReception indicates an expected call of CloseLastReception.
func (mr *MockreceptionsServiceMockRecorder) CloseLastReception(ctx, pvzID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseLastReception", reflect.TypeOf((*MockreceptionsService)(nil).CloseLastReception), ctx, pvzID)
}

// Create mocks base method.
func (m *MockreceptionsService) Create(ctx context.Context, createIn receptions.CreateIn) (*receptions.CreateOut, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createIn)
	ret0, _ := ret[0].(*receptions.CreateOut)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockreceptionsServiceMockRecorder) Create(ctx, createIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockreceptionsService)(nil).Create), ctx, createIn)
}
