// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=./mocks/service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/valeragav/avito-pvz-service/internal/domain"
	dto "github.com/valeragav/avito-pvz-service/internal/usecase/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockpvzService is a mock of pvzService interface.
type MockpvzService struct {
	ctrl     *gomock.Controller
	recorder *MockpvzServiceMockRecorder
	isgomock struct{}
}

// MockpvzServiceMockRecorder is the mock recorder for MockpvzService.
type MockpvzServiceMockRecorder struct {
	mock *MockpvzService
}

// NewMockpvzService creates a new mock instance.
func NewMockpvzService(ctrl *gomock.Controller) *MockpvzService {
	mock := &MockpvzService{ctrl: ctrl}
	mock.recorder = &MockpvzServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpvzService) EXPECT() *MockpvzServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockpvzService) Create(ctx context.Context, createIn dto.PVZCreate) (*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, createIn)
	ret0, _ := ret[0].(*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockpvzServiceMockRecorder) Create(ctx, createIn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockpvzService)(nil).Create), ctx, createIn)
}

// List mocks base method.
func (m *MockpvzService) List(ctx context.Context, pvzListParams *dto.PVZListParams) ([]*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, pvzListParams)
	ret0, _ := ret[0].([]*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockpvzServiceMockRecorder) List(ctx, pvzListParams any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockpvzService)(nil).List), ctx, pvzListParams)
}
