// Code generated by MockGen. DO NOT EDIT.
// Source: reception.go
//
// Generated by this command:
//
//	mockgen -source=reception.go -destination=./mocks/reception_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/valeragav/avito-pvz-service/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockreceptionRepo is a mock of receptionRepo interface.
type MockreceptionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionRepoMockRecorder
	isgomock struct{}
}

// MockreceptionRepoMockRecorder is the mock recorder for MockreceptionRepo.
type MockreceptionRepoMockRecorder struct {
	mock *MockreceptionRepo
}

// NewMockreceptionRepo creates a new mock instance.
func NewMockreceptionRepo(ctrl *gomock.Controller) *MockreceptionRepo {
	mock := &MockreceptionRepo{ctrl: ctrl}
	mock.recorder = &MockreceptionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionRepo) EXPECT() *MockreceptionRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockreceptionRepo) Create(ctx context.Context, reception domain.Reception) (*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, reception)
	ret0, _ := ret[0].(*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockreceptionRepoMockRecorder) Create(ctx, reception any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockreceptionRepo)(nil).Create), ctx, reception)
}

// FindByStatus mocks base method.
func (m *MockreceptionRepo) FindByStatus(ctx context.Context, statusName domain.ReceptionStatusCode, filter domain.Reception) (*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByStatus", ctx, statusName, filter)
	ret0, _ := ret[0].(*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByStatus indicates an expected call of FindByStatus.
func (mr *MockreceptionRepoMockRecorder) FindByStatus(ctx, statusName, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByStatus", reflect.TypeOf((*MockreceptionRepo)(nil).FindByStatus), ctx, statusName, filter)
}

// Update mocks base method.
func (m *MockreceptionRepo) Update(ctx context.Context, receptionID uuid.UUID, update domain.Reception) (*domain.Reception, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, receptionID, update)
	ret0, _ := ret[0].(*domain.Reception)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockreceptionRepoMockRecorder) Update(ctx, receptionID, update any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockreceptionRepo)(nil).Update), ctx, receptionID, update)
}

// MockreceptionStatusRepo is a mock of receptionStatusRepo interface.
type MockreceptionStatusRepo struct {
	ctrl     *gomock.Controller
	recorder *MockreceptionStatusRepoMockRecorder
	isgomock struct{}
}

// MockreceptionStatusRepoMockRecorder is the mock recorder for MockreceptionStatusRepo.
type MockreceptionStatusRepoMockRecorder struct {
	mock *MockreceptionStatusRepo
}

// NewMockreceptionStatusRepo creates a new mock instance.
func NewMockreceptionStatusRepo(ctrl *gomock.Controller) *MockreceptionStatusRepo {
	mock := &MockreceptionStatusRepo{ctrl: ctrl}
	mock.recorder = &MockreceptionStatusRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockreceptionStatusRepo) EXPECT() *MockreceptionStatusRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockreceptionStatusRepo) Get(ctx context.Context, filter domain.ReceptionStatus) (*domain.ReceptionStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*domain.ReceptionStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockreceptionStatusRepoMockRecorder) Get(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockreceptionStatusRepo)(nil).Get), ctx, filter)
}

// MockpvzRepo is a mock of pvzRepo interface.
type MockpvzRepo struct {
	ctrl     *gomock.Controller
	recorder *MockpvzRepoMockRecorder
	isgomock struct{}
}

// MockpvzRepoMockRecorder is the mock recorder for MockpvzRepo.
type MockpvzRepoMockRecorder struct {
	mock *MockpvzRepo
}

// NewMockpvzRepo creates a new mock instance.
func NewMockpvzRepo(ctrl *gomock.Controller) *MockpvzRepo {
	mock := &MockpvzRepo{ctrl: ctrl}
	mock.recorder = &MockpvzRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpvzRepo) EXPECT() *MockpvzRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockpvzRepo) Get(ctx context.Context, filter domain.PVZ) (*domain.PVZ, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].(*domain.PVZ)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockpvzRepoMockRecorder) Get(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockpvzRepo)(nil).Get), ctx, filter)
}
